# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlateLayoutWidgetUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlateLayoutWidget(object):
    def setupUi(self, PlateLayoutWidget):
        PlateLayoutWidget.setObjectName("PlateLayoutWidget")
        PlateLayoutWidget.resize(1102, 822)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(PlateLayoutWidget)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widgetInfo = QtWidgets.QWidget(PlateLayoutWidget)
        self.widgetInfo.setObjectName("widgetInfo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetInfo)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelWelcome = QtWidgets.QLabel(self.widgetInfo)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelWelcome.setPalette(palette)
        self.labelWelcome.setObjectName("labelWelcome")
        self.horizontalLayout.addWidget(self.labelWelcome)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelInfo = QtWidgets.QLabel(self.widgetInfo)
        self.labelInfo.setObjectName("labelInfo")
        self.verticalLayout.addWidget(self.labelInfo)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonInfo = QtWidgets.QPushButton(self.widgetInfo)
        self.pushButtonInfo.setObjectName("pushButtonInfo")
        self.horizontalLayout_2.addWidget(self.pushButtonInfo)
        self.verticalLayout_20.addWidget(self.widgetInfo)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(PlateLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 7, 1, 1)
        self.label_8 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 8, 1, 1)
        self.label_9 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 9, 1, 1)
        self.label_10 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 10, 1, 1)
        self.label_11 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 1, 1, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 2, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 1, 3, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 1, 4, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout.addWidget(self.toolButton_8, 1, 5, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 1, 6, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout.addWidget(self.toolButton_5, 1, 7, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout.addWidget(self.toolButton_7, 1, 8, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout.addWidget(self.toolButton_9, 1, 9, 1, 1)
        self.toolButton_10 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_10.setObjectName("toolButton_10")
        self.gridLayout.addWidget(self.toolButton_10, 1, 10, 1, 1)
        self.label_12 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.toolButton_11 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_11.setObjectName("toolButton_11")
        self.gridLayout.addWidget(self.toolButton_11, 2, 1, 1, 1)
        self.toolButton_14 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_14.setObjectName("toolButton_14")
        self.gridLayout.addWidget(self.toolButton_14, 2, 2, 1, 1)
        self.toolButton_13 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_13.setObjectName("toolButton_13")
        self.gridLayout.addWidget(self.toolButton_13, 2, 3, 1, 1)
        self.toolButton_18 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_18.setObjectName("toolButton_18")
        self.gridLayout.addWidget(self.toolButton_18, 2, 4, 1, 1)
        self.toolButton_12 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_12.setObjectName("toolButton_12")
        self.gridLayout.addWidget(self.toolButton_12, 2, 5, 1, 1)
        self.toolButton_15 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_15.setObjectName("toolButton_15")
        self.gridLayout.addWidget(self.toolButton_15, 2, 6, 1, 1)
        self.toolButton_19 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_19.setObjectName("toolButton_19")
        self.gridLayout.addWidget(self.toolButton_19, 2, 7, 1, 1)
        self.toolButton_17 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_17.setObjectName("toolButton_17")
        self.gridLayout.addWidget(self.toolButton_17, 2, 8, 1, 1)
        self.toolButton_20 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_20.setObjectName("toolButton_20")
        self.gridLayout.addWidget(self.toolButton_20, 2, 9, 1, 1)
        self.toolButton_16 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_16.setObjectName("toolButton_16")
        self.gridLayout.addWidget(self.toolButton_16, 2, 10, 1, 1)
        self.label_13 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.toolButton_29 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_29.setObjectName("toolButton_29")
        self.gridLayout.addWidget(self.toolButton_29, 3, 1, 1, 1)
        self.toolButton_38 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_38.setObjectName("toolButton_38")
        self.gridLayout.addWidget(self.toolButton_38, 3, 2, 1, 1)
        self.toolButton_22 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_22.setObjectName("toolButton_22")
        self.gridLayout.addWidget(self.toolButton_22, 3, 3, 1, 1)
        self.toolButton_23 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_23.setObjectName("toolButton_23")
        self.gridLayout.addWidget(self.toolButton_23, 3, 4, 1, 1)
        self.toolButton_28 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_28.setObjectName("toolButton_28")
        self.gridLayout.addWidget(self.toolButton_28, 3, 5, 1, 1)
        self.toolButton_37 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_37.setObjectName("toolButton_37")
        self.gridLayout.addWidget(self.toolButton_37, 3, 6, 1, 1)
        self.toolButton_33 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_33.setObjectName("toolButton_33")
        self.gridLayout.addWidget(self.toolButton_33, 3, 7, 1, 1)
        self.toolButton_40 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_40.setObjectName("toolButton_40")
        self.gridLayout.addWidget(self.toolButton_40, 3, 8, 1, 1)
        self.toolButton_34 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_34.setObjectName("toolButton_34")
        self.gridLayout.addWidget(self.toolButton_34, 3, 9, 1, 1)
        self.toolButton_39 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_39.setObjectName("toolButton_39")
        self.gridLayout.addWidget(self.toolButton_39, 3, 10, 1, 1)
        self.label_16 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.toolButton_36 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_36.setObjectName("toolButton_36")
        self.gridLayout.addWidget(self.toolButton_36, 4, 1, 1, 1)
        self.toolButton_35 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_35.setObjectName("toolButton_35")
        self.gridLayout.addWidget(self.toolButton_35, 4, 2, 1, 1)
        self.toolButton_32 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_32.setObjectName("toolButton_32")
        self.gridLayout.addWidget(self.toolButton_32, 4, 3, 1, 1)
        self.toolButton_31 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_31.setObjectName("toolButton_31")
        self.gridLayout.addWidget(self.toolButton_31, 4, 4, 1, 1)
        self.toolButton_26 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_26.setObjectName("toolButton_26")
        self.gridLayout.addWidget(self.toolButton_26, 4, 5, 1, 1)
        self.toolButton_24 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_24.setObjectName("toolButton_24")
        self.gridLayout.addWidget(self.toolButton_24, 4, 6, 1, 1)
        self.toolButton_30 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_30.setObjectName("toolButton_30")
        self.gridLayout.addWidget(self.toolButton_30, 4, 7, 1, 1)
        self.toolButton_27 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_27.setObjectName("toolButton_27")
        self.gridLayout.addWidget(self.toolButton_27, 4, 8, 1, 1)
        self.toolButton_21 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_21.setObjectName("toolButton_21")
        self.gridLayout.addWidget(self.toolButton_21, 4, 9, 1, 1)
        self.toolButton_25 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_25.setObjectName("toolButton_25")
        self.gridLayout.addWidget(self.toolButton_25, 4, 10, 1, 1)
        self.label_15 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 1)
        self.toolButton_44 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_44.setObjectName("toolButton_44")
        self.gridLayout.addWidget(self.toolButton_44, 5, 1, 1, 1)
        self.toolButton_63 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_63.setObjectName("toolButton_63")
        self.gridLayout.addWidget(self.toolButton_63, 5, 2, 1, 1)
        self.toolButton_74 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_74.setObjectName("toolButton_74")
        self.gridLayout.addWidget(self.toolButton_74, 5, 3, 1, 1)
        self.toolButton_48 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_48.setObjectName("toolButton_48")
        self.gridLayout.addWidget(self.toolButton_48, 5, 4, 1, 1)
        self.toolButton_71 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_71.setObjectName("toolButton_71")
        self.gridLayout.addWidget(self.toolButton_71, 5, 5, 1, 1)
        self.toolButton_59 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_59.setObjectName("toolButton_59")
        self.gridLayout.addWidget(self.toolButton_59, 5, 6, 1, 1)
        self.toolButton_56 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_56.setObjectName("toolButton_56")
        self.gridLayout.addWidget(self.toolButton_56, 5, 7, 1, 1)
        self.toolButton_45 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_45.setObjectName("toolButton_45")
        self.gridLayout.addWidget(self.toolButton_45, 5, 8, 1, 1)
        self.toolButton_49 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_49.setObjectName("toolButton_49")
        self.gridLayout.addWidget(self.toolButton_49, 5, 9, 1, 1)
        self.toolButton_80 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_80.setObjectName("toolButton_80")
        self.gridLayout.addWidget(self.toolButton_80, 5, 10, 1, 1)
        self.label_14 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 0, 1, 1)
        self.toolButton_69 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_69.setObjectName("toolButton_69")
        self.gridLayout.addWidget(self.toolButton_69, 6, 1, 1, 1)
        self.toolButton_41 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_41.setObjectName("toolButton_41")
        self.gridLayout.addWidget(self.toolButton_41, 6, 2, 1, 1)
        self.toolButton_79 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_79.setObjectName("toolButton_79")
        self.gridLayout.addWidget(self.toolButton_79, 6, 3, 1, 1)
        self.toolButton_51 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_51.setObjectName("toolButton_51")
        self.gridLayout.addWidget(self.toolButton_51, 6, 4, 1, 1)
        self.toolButton_57 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_57.setObjectName("toolButton_57")
        self.gridLayout.addWidget(self.toolButton_57, 6, 5, 1, 1)
        self.toolButton_62 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_62.setObjectName("toolButton_62")
        self.gridLayout.addWidget(self.toolButton_62, 6, 6, 1, 1)
        self.toolButton_67 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_67.setObjectName("toolButton_67")
        self.gridLayout.addWidget(self.toolButton_67, 6, 7, 1, 1)
        self.toolButton_68 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_68.setObjectName("toolButton_68")
        self.gridLayout.addWidget(self.toolButton_68, 6, 8, 1, 1)
        self.toolButton_61 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_61.setObjectName("toolButton_61")
        self.gridLayout.addWidget(self.toolButton_61, 6, 9, 1, 1)
        self.toolButton_75 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_75.setObjectName("toolButton_75")
        self.gridLayout.addWidget(self.toolButton_75, 6, 10, 1, 1)
        self.label_18 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 7, 0, 1, 1)
        self.toolButton_65 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_65.setObjectName("toolButton_65")
        self.gridLayout.addWidget(self.toolButton_65, 7, 1, 1, 1)
        self.toolButton_73 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_73.setObjectName("toolButton_73")
        self.gridLayout.addWidget(self.toolButton_73, 7, 2, 1, 1)
        self.toolButton_76 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_76.setObjectName("toolButton_76")
        self.gridLayout.addWidget(self.toolButton_76, 7, 3, 1, 1)
        self.toolButton_43 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_43.setObjectName("toolButton_43")
        self.gridLayout.addWidget(self.toolButton_43, 7, 4, 1, 1)
        self.toolButton_46 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_46.setObjectName("toolButton_46")
        self.gridLayout.addWidget(self.toolButton_46, 7, 5, 1, 1)
        self.toolButton_66 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_66.setObjectName("toolButton_66")
        self.gridLayout.addWidget(self.toolButton_66, 7, 6, 1, 1)
        self.toolButton_53 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_53.setObjectName("toolButton_53")
        self.gridLayout.addWidget(self.toolButton_53, 7, 7, 1, 1)
        self.toolButton_64 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_64.setObjectName("toolButton_64")
        self.gridLayout.addWidget(self.toolButton_64, 7, 8, 1, 1)
        self.toolButton_55 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_55.setObjectName("toolButton_55")
        self.gridLayout.addWidget(self.toolButton_55, 7, 9, 1, 1)
        self.toolButton_54 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_54.setObjectName("toolButton_54")
        self.gridLayout.addWidget(self.toolButton_54, 7, 10, 1, 1)
        self.label_19 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 8, 0, 1, 1)
        self.toolButton_52 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_52.setObjectName("toolButton_52")
        self.gridLayout.addWidget(self.toolButton_52, 8, 1, 1, 1)
        self.toolButton_42 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_42.setObjectName("toolButton_42")
        self.gridLayout.addWidget(self.toolButton_42, 8, 2, 1, 1)
        self.toolButton_58 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_58.setObjectName("toolButton_58")
        self.gridLayout.addWidget(self.toolButton_58, 8, 3, 1, 1)
        self.toolButton_47 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_47.setObjectName("toolButton_47")
        self.gridLayout.addWidget(self.toolButton_47, 8, 4, 1, 1)
        self.toolButton_70 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_70.setObjectName("toolButton_70")
        self.gridLayout.addWidget(self.toolButton_70, 8, 5, 1, 1)
        self.toolButton_60 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_60.setObjectName("toolButton_60")
        self.gridLayout.addWidget(self.toolButton_60, 8, 6, 1, 1)
        self.toolButton_77 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_77.setObjectName("toolButton_77")
        self.gridLayout.addWidget(self.toolButton_77, 8, 7, 1, 1)
        self.toolButton_72 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_72.setObjectName("toolButton_72")
        self.gridLayout.addWidget(self.toolButton_72, 8, 8, 1, 1)
        self.toolButton_50 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_50.setObjectName("toolButton_50")
        self.gridLayout.addWidget(self.toolButton_50, 8, 9, 1, 1)
        self.toolButton_78 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_78.setObjectName("toolButton_78")
        self.gridLayout.addWidget(self.toolButton_78, 8, 10, 1, 1)
        self.label_17 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 9, 0, 1, 1)
        self.toolButton_89 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_89.setObjectName("toolButton_89")
        self.gridLayout.addWidget(self.toolButton_89, 9, 1, 1, 1)
        self.toolButton_98 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_98.setObjectName("toolButton_98")
        self.gridLayout.addWidget(self.toolButton_98, 9, 2, 1, 1)
        self.toolButton_82 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_82.setObjectName("toolButton_82")
        self.gridLayout.addWidget(self.toolButton_82, 9, 3, 1, 1)
        self.toolButton_83 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_83.setObjectName("toolButton_83")
        self.gridLayout.addWidget(self.toolButton_83, 9, 4, 1, 1)
        self.toolButton_88 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_88.setObjectName("toolButton_88")
        self.gridLayout.addWidget(self.toolButton_88, 9, 5, 1, 1)
        self.toolButton_97 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_97.setObjectName("toolButton_97")
        self.gridLayout.addWidget(self.toolButton_97, 9, 6, 1, 1)
        self.toolButton_93 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_93.setObjectName("toolButton_93")
        self.gridLayout.addWidget(self.toolButton_93, 9, 7, 1, 1)
        self.toolButton_100 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_100.setObjectName("toolButton_100")
        self.gridLayout.addWidget(self.toolButton_100, 9, 8, 1, 1)
        self.toolButton_94 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_94.setObjectName("toolButton_94")
        self.gridLayout.addWidget(self.toolButton_94, 9, 9, 1, 1)
        self.toolButton_99 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_99.setObjectName("toolButton_99")
        self.gridLayout.addWidget(self.toolButton_99, 9, 10, 1, 1)
        self.label_20 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 10, 0, 1, 1)
        self.toolButton_96 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_96.setObjectName("toolButton_96")
        self.gridLayout.addWidget(self.toolButton_96, 10, 1, 1, 1)
        self.toolButton_95 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_95.setObjectName("toolButton_95")
        self.gridLayout.addWidget(self.toolButton_95, 10, 2, 1, 1)
        self.toolButton_92 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_92.setObjectName("toolButton_92")
        self.gridLayout.addWidget(self.toolButton_92, 10, 3, 1, 1)
        self.toolButton_91 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_91.setObjectName("toolButton_91")
        self.gridLayout.addWidget(self.toolButton_91, 10, 4, 1, 1)
        self.toolButton_86 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_86.setObjectName("toolButton_86")
        self.gridLayout.addWidget(self.toolButton_86, 10, 5, 1, 1)
        self.toolButton_84 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_84.setObjectName("toolButton_84")
        self.gridLayout.addWidget(self.toolButton_84, 10, 6, 1, 1)
        self.toolButton_90 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_90.setObjectName("toolButton_90")
        self.gridLayout.addWidget(self.toolButton_90, 10, 7, 1, 1)
        self.toolButton_87 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_87.setObjectName("toolButton_87")
        self.gridLayout.addWidget(self.toolButton_87, 10, 8, 1, 1)
        self.toolButton_81 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_81.setObjectName("toolButton_81")
        self.gridLayout.addWidget(self.toolButton_81, 10, 9, 1, 1)
        self.toolButton_85 = QtWidgets.QToolButton(PlateLayoutWidget)
        self.toolButton_85.setObjectName("toolButton_85")
        self.gridLayout.addWidget(self.toolButton_85, 10, 10, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_21 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(PlateLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_22 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.pushButton = QtWidgets.QPushButton(PlateLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(PlateLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.label_23 = QtWidgets.QLabel(PlateLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_2.addWidget(self.label_23)
        self.pushButton_3 = QtWidgets.QPushButton(PlateLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_20.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_2 = QtWidgets.QWidget(PlateLayoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_24 = QtWidgets.QLabel(self.widget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.label_27 = QtWidgets.QLabel(self.widget_2)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.pushButton_5)
        self.label_28 = QtWidgets.QLabel(self.widget_2)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_5.addWidget(self.label_28)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.label_29 = QtWidgets.QLabel(self.widget_2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_6.addWidget(self.label_29)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_10.addWidget(self.pushButton_10)
        self.label_33 = QtWidgets.QLabel(self.widget_2)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_10.addWidget(self.label_33)
        self.gridLayout_3.addLayout(self.verticalLayout_10, 0, 3, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_7.addWidget(self.pushButton_7)
        self.label_30 = QtWidgets.QLabel(self.widget_2)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_7.addWidget(self.label_30)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_8.addWidget(self.pushButton_8)
        self.label_31 = QtWidgets.QLabel(self.widget_2)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_8.addWidget(self.label_31)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_9.addWidget(self.pushButton_9)
        self.label_32 = QtWidgets.QLabel(self.widget_2)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_9.addWidget(self.label_32)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 1, 3, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_3)
        self.horizontalLayout_8.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(PlateLayoutWidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_4.addWidget(self.comboBox_3, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.widget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 0, 0, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_14.addWidget(self.pushButton_12)
        self.label_36 = QtWidgets.QLabel(self.widget_3)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_14.addWidget(self.label_36)
        self.gridLayout_5.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_15.addWidget(self.pushButton_13)
        self.label_37 = QtWidgets.QLabel(self.widget_3)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_15.addWidget(self.label_37)
        self.gridLayout_5.addLayout(self.verticalLayout_15, 0, 1, 1, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_18.addWidget(self.pushButton_16)
        self.label_40 = QtWidgets.QLabel(self.widget_3)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_18.addWidget(self.label_40)
        self.gridLayout_5.addLayout(self.verticalLayout_18, 1, 0, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_5)
        self.horizontalLayout_8.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(PlateLayoutWidget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_6.addWidget(self.comboBox_4, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.widget_4)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 0, 0, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_6)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_16.addWidget(self.pushButton_14)
        self.label_38 = QtWidgets.QLabel(self.widget_4)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_16.addWidget(self.label_38)
        self.gridLayout_7.addLayout(self.verticalLayout_16, 0, 0, 1, 1)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.pushButton_17 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_19.addWidget(self.pushButton_17)
        self.label_41 = QtWidgets.QLabel(self.widget_4)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_19.addWidget(self.label_41)
        self.gridLayout_7.addLayout(self.verticalLayout_19, 1, 0, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_7)
        self.horizontalLayout_8.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(PlateLayoutWidget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_35 = QtWidgets.QLabel(self.widget_5)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_6.addWidget(self.label_35)
        self.radioButton = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_6.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_6.addWidget(self.radioButton_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_17.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_5)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addWidget(self.widget_5)
        self.verticalLayout_20.addLayout(self.horizontalLayout_8)
        self.widget = QtWidgets.QWidget(PlateLayoutWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButtonCancel = QtWidgets.QPushButton(self.widget)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_3.addWidget(self.pushButtonCancel)
        self.pushButtonBack = QtWidgets.QPushButton(self.widget)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.horizontalLayout_3.addWidget(self.pushButtonBack)
        self.pushButtonSave = QtWidgets.QPushButton(self.widget)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_3.addWidget(self.pushButtonSave)
        self.verticalLayout_20.addWidget(self.widget)
        self.verticalLayout_20.setStretch(2, 1)

        self.retranslateUi(PlateLayoutWidget)
        QtCore.QMetaObject.connectSlotsByName(PlateLayoutWidget)

    def retranslateUi(self, PlateLayoutWidget):
        _translate = QtCore.QCoreApplication.translate
        PlateLayoutWidget.setWindowTitle(_translate("PlateLayoutWidget", "PlateLayout"))
        self.labelWelcome.setText(_translate("PlateLayoutWidget", "Step 1: Protocol Setting for \"mTH1 2 9 17 22Treg 17 Plex\""))
        self.labelInfo.setText(_translate("PlateLayoutWidget", "Instructions:  Name this protocol and select the acquisition settings. Press Next to continue."))
        self.pushButtonInfo.setText(_translate("PlateLayoutWidget", "info"))
        self.label.setText(_translate("PlateLayoutWidget", "1"))
        self.label_2.setText(_translate("PlateLayoutWidget", "2"))
        self.label_3.setText(_translate("PlateLayoutWidget", "3"))
        self.label_4.setText(_translate("PlateLayoutWidget", "4"))
        self.label_5.setText(_translate("PlateLayoutWidget", "5"))
        self.label_6.setText(_translate("PlateLayoutWidget", "6"))
        self.label_7.setText(_translate("PlateLayoutWidget", "7"))
        self.label_8.setText(_translate("PlateLayoutWidget", "8"))
        self.label_9.setText(_translate("PlateLayoutWidget", "9"))
        self.label_10.setText(_translate("PlateLayoutWidget", "10"))
        self.label_11.setText(_translate("PlateLayoutWidget", "A"))
        self.toolButton.setText(_translate("PlateLayoutWidget", "1"))
        self.toolButton_2.setText(_translate("PlateLayoutWidget", "2"))
        self.toolButton_3.setText(_translate("PlateLayoutWidget", "3"))
        self.toolButton_4.setText(_translate("PlateLayoutWidget", "4"))
        self.toolButton_8.setText(_translate("PlateLayoutWidget", "5"))
        self.toolButton_6.setText(_translate("PlateLayoutWidget", "6"))
        self.toolButton_5.setText(_translate("PlateLayoutWidget", "7"))
        self.toolButton_7.setText(_translate("PlateLayoutWidget", "8"))
        self.toolButton_9.setText(_translate("PlateLayoutWidget", "9"))
        self.toolButton_10.setText(_translate("PlateLayoutWidget", "10"))
        self.label_12.setText(_translate("PlateLayoutWidget", "B"))
        self.toolButton_11.setText(_translate("PlateLayoutWidget", "11"))
        self.toolButton_14.setText(_translate("PlateLayoutWidget", "12"))
        self.toolButton_13.setText(_translate("PlateLayoutWidget", "13"))
        self.toolButton_18.setText(_translate("PlateLayoutWidget", "14"))
        self.toolButton_12.setText(_translate("PlateLayoutWidget", "15"))
        self.toolButton_15.setText(_translate("PlateLayoutWidget", "16"))
        self.toolButton_19.setText(_translate("PlateLayoutWidget", "17"))
        self.toolButton_17.setText(_translate("PlateLayoutWidget", "18"))
        self.toolButton_20.setText(_translate("PlateLayoutWidget", "19"))
        self.toolButton_16.setText(_translate("PlateLayoutWidget", "20"))
        self.label_13.setText(_translate("PlateLayoutWidget", "C"))
        self.toolButton_29.setText(_translate("PlateLayoutWidget", "21"))
        self.toolButton_38.setText(_translate("PlateLayoutWidget", "22"))
        self.toolButton_22.setText(_translate("PlateLayoutWidget", "23"))
        self.toolButton_23.setText(_translate("PlateLayoutWidget", "24"))
        self.toolButton_28.setText(_translate("PlateLayoutWidget", "25"))
        self.toolButton_37.setText(_translate("PlateLayoutWidget", "26"))
        self.toolButton_33.setText(_translate("PlateLayoutWidget", "27"))
        self.toolButton_40.setText(_translate("PlateLayoutWidget", "28"))
        self.toolButton_34.setText(_translate("PlateLayoutWidget", "29"))
        self.toolButton_39.setText(_translate("PlateLayoutWidget", "30"))
        self.label_16.setText(_translate("PlateLayoutWidget", "D"))
        self.toolButton_36.setText(_translate("PlateLayoutWidget", "31"))
        self.toolButton_35.setText(_translate("PlateLayoutWidget", "32"))
        self.toolButton_32.setText(_translate("PlateLayoutWidget", "33"))
        self.toolButton_31.setText(_translate("PlateLayoutWidget", "34"))
        self.toolButton_26.setText(_translate("PlateLayoutWidget", "35"))
        self.toolButton_24.setText(_translate("PlateLayoutWidget", "36"))
        self.toolButton_30.setText(_translate("PlateLayoutWidget", "37"))
        self.toolButton_27.setText(_translate("PlateLayoutWidget", "38"))
        self.toolButton_21.setText(_translate("PlateLayoutWidget", "39"))
        self.toolButton_25.setText(_translate("PlateLayoutWidget", "40"))
        self.label_15.setText(_translate("PlateLayoutWidget", "E"))
        self.toolButton_44.setText(_translate("PlateLayoutWidget", "41"))
        self.toolButton_63.setText(_translate("PlateLayoutWidget", "42"))
        self.toolButton_74.setText(_translate("PlateLayoutWidget", "43"))
        self.toolButton_48.setText(_translate("PlateLayoutWidget", "44"))
        self.toolButton_71.setText(_translate("PlateLayoutWidget", "45"))
        self.toolButton_59.setText(_translate("PlateLayoutWidget", "46"))
        self.toolButton_56.setText(_translate("PlateLayoutWidget", "47"))
        self.toolButton_45.setText(_translate("PlateLayoutWidget", "48"))
        self.toolButton_49.setText(_translate("PlateLayoutWidget", "49"))
        self.toolButton_80.setText(_translate("PlateLayoutWidget", "50"))
        self.label_14.setText(_translate("PlateLayoutWidget", "F"))
        self.toolButton_69.setText(_translate("PlateLayoutWidget", "51"))
        self.toolButton_41.setText(_translate("PlateLayoutWidget", "52"))
        self.toolButton_79.setText(_translate("PlateLayoutWidget", "53"))
        self.toolButton_51.setText(_translate("PlateLayoutWidget", "54"))
        self.toolButton_57.setText(_translate("PlateLayoutWidget", "55"))
        self.toolButton_62.setText(_translate("PlateLayoutWidget", "56"))
        self.toolButton_67.setText(_translate("PlateLayoutWidget", "57"))
        self.toolButton_68.setText(_translate("PlateLayoutWidget", "58"))
        self.toolButton_61.setText(_translate("PlateLayoutWidget", "59"))
        self.toolButton_75.setText(_translate("PlateLayoutWidget", "60"))
        self.label_18.setText(_translate("PlateLayoutWidget", "G"))
        self.toolButton_65.setText(_translate("PlateLayoutWidget", "61"))
        self.toolButton_73.setText(_translate("PlateLayoutWidget", "62"))
        self.toolButton_76.setText(_translate("PlateLayoutWidget", "63"))
        self.toolButton_43.setText(_translate("PlateLayoutWidget", "64"))
        self.toolButton_46.setText(_translate("PlateLayoutWidget", "65"))
        self.toolButton_66.setText(_translate("PlateLayoutWidget", "66"))
        self.toolButton_53.setText(_translate("PlateLayoutWidget", "67"))
        self.toolButton_64.setText(_translate("PlateLayoutWidget", "68"))
        self.toolButton_55.setText(_translate("PlateLayoutWidget", "69"))
        self.toolButton_54.setText(_translate("PlateLayoutWidget", "70"))
        self.label_19.setText(_translate("PlateLayoutWidget", "H"))
        self.toolButton_52.setText(_translate("PlateLayoutWidget", "71"))
        self.toolButton_42.setText(_translate("PlateLayoutWidget", "72"))
        self.toolButton_58.setText(_translate("PlateLayoutWidget", "73"))
        self.toolButton_47.setText(_translate("PlateLayoutWidget", "74"))
        self.toolButton_70.setText(_translate("PlateLayoutWidget", "75"))
        self.toolButton_60.setText(_translate("PlateLayoutWidget", "76"))
        self.toolButton_77.setText(_translate("PlateLayoutWidget", "77"))
        self.toolButton_72.setText(_translate("PlateLayoutWidget", "78"))
        self.toolButton_50.setText(_translate("PlateLayoutWidget", "79"))
        self.toolButton_78.setText(_translate("PlateLayoutWidget", "80"))
        self.label_17.setText(_translate("PlateLayoutWidget", "I"))
        self.toolButton_89.setText(_translate("PlateLayoutWidget", "81"))
        self.toolButton_98.setText(_translate("PlateLayoutWidget", "82"))
        self.toolButton_82.setText(_translate("PlateLayoutWidget", "83"))
        self.toolButton_83.setText(_translate("PlateLayoutWidget", "84"))
        self.toolButton_88.setText(_translate("PlateLayoutWidget", "85"))
        self.toolButton_97.setText(_translate("PlateLayoutWidget", "86"))
        self.toolButton_93.setText(_translate("PlateLayoutWidget", "87"))
        self.toolButton_100.setText(_translate("PlateLayoutWidget", "88"))
        self.toolButton_94.setText(_translate("PlateLayoutWidget", "89"))
        self.toolButton_99.setText(_translate("PlateLayoutWidget", "90"))
        self.label_20.setText(_translate("PlateLayoutWidget", "J"))
        self.toolButton_96.setText(_translate("PlateLayoutWidget", "91"))
        self.toolButton_95.setText(_translate("PlateLayoutWidget", "92"))
        self.toolButton_92.setText(_translate("PlateLayoutWidget", "93"))
        self.toolButton_91.setText(_translate("PlateLayoutWidget", "94"))
        self.toolButton_86.setText(_translate("PlateLayoutWidget", "95"))
        self.toolButton_84.setText(_translate("PlateLayoutWidget", "96"))
        self.toolButton_90.setText(_translate("PlateLayoutWidget", "97"))
        self.toolButton_87.setText(_translate("PlateLayoutWidget", "98"))
        self.toolButton_81.setText(_translate("PlateLayoutWidget", "99"))
        self.toolButton_85.setText(_translate("PlateLayoutWidget", "100"))
        self.label_21.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.label_22.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.pushButton_2.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_23.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_3.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_24.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.label_25.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_4.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_27.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_5.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_28.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_6.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_29.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_10.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_33.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_7.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_30.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_8.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_31.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_9.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_32.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.label_26.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_12.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_36.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_13.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_37.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_16.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_40.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.label_34.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_14.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_38.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.pushButton_17.setText(_translate("PlateLayoutWidget", "PushButton"))
        self.label_41.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.label_35.setText(_translate("PlateLayoutWidget", "TextLabel"))
        self.radioButton.setText(_translate("PlateLayoutWidget", "RadioButton"))
        self.radioButton_2.setText(_translate("PlateLayoutWidget", "RadioButton"))
        self.groupBox.setTitle(_translate("PlateLayoutWidget", "GroupBox"))
        self.groupBox_2.setTitle(_translate("PlateLayoutWidget", "GroupBox"))
        self.pushButtonCancel.setText(_translate("PlateLayoutWidget", "Cancel"))
        self.pushButtonBack.setText(_translate("PlateLayoutWidget", "Back"))
        self.pushButtonSave.setText(_translate("PlateLayoutWidget", "Save"))


