# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnalytesWidgetUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnalytesWidget(object):
    def setupUi(self, AnalytesWidget):
        AnalytesWidget.setObjectName("AnalytesWidget")
        AnalytesWidget.resize(1102, 822)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(AnalytesWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widgetInfo = QtWidgets.QWidget(AnalytesWidget)
        self.widgetInfo.setObjectName("widgetInfo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetInfo)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelWelcome = QtWidgets.QLabel(self.widgetInfo)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelWelcome.setPalette(palette)
        self.labelWelcome.setObjectName("labelWelcome")
        self.horizontalLayout.addWidget(self.labelWelcome)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelInfo = QtWidgets.QLabel(self.widgetInfo)
        self.labelInfo.setObjectName("labelInfo")
        self.verticalLayout.addWidget(self.labelInfo)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonInfo = QtWidgets.QPushButton(self.widgetInfo)
        self.pushButtonInfo.setObjectName("pushButtonInfo")
        self.horizontalLayout_2.addWidget(self.pushButtonInfo)
        self.verticalLayout_6.addWidget(self.widgetInfo)
        self.groupBox = QtWidgets.QGroupBox(AnalytesWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 0, 1, 1, 1)
        self.toolButton_40 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_40.setObjectName("toolButton_40")
        self.gridLayout.addWidget(self.toolButton_40, 2, 7, 1, 1)
        self.toolButton_34 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_34.setObjectName("toolButton_34")
        self.gridLayout.addWidget(self.toolButton_34, 2, 8, 1, 1)
        self.toolButton_21 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_21.setObjectName("toolButton_21")
        self.gridLayout.addWidget(self.toolButton_21, 3, 8, 1, 1)
        self.toolButton_25 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_25.setObjectName("toolButton_25")
        self.gridLayout.addWidget(self.toolButton_25, 3, 9, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout.addWidget(self.toolButton_7, 0, 7, 1, 1)
        self.toolButton_16 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_16.setObjectName("toolButton_16")
        self.gridLayout.addWidget(self.toolButton_16, 1, 9, 1, 1)
        self.toolButton_28 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_28.setObjectName("toolButton_28")
        self.gridLayout.addWidget(self.toolButton_28, 2, 4, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 0, 2, 1, 1)
        self.toolButton_30 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_30.setObjectName("toolButton_30")
        self.gridLayout.addWidget(self.toolButton_30, 3, 6, 1, 1)
        self.toolButton_31 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_31.setObjectName("toolButton_31")
        self.gridLayout.addWidget(self.toolButton_31, 3, 3, 1, 1)
        self.toolButton_11 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_11.setObjectName("toolButton_11")
        self.gridLayout.addWidget(self.toolButton_11, 1, 0, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout.addWidget(self.toolButton_8, 0, 4, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout.addWidget(self.toolButton_9, 0, 8, 1, 1)
        self.toolButton_18 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_18.setObjectName("toolButton_18")
        self.gridLayout.addWidget(self.toolButton_18, 1, 3, 1, 1)
        self.toolButton_38 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_38.setObjectName("toolButton_38")
        self.gridLayout.addWidget(self.toolButton_38, 2, 1, 1, 1)
        self.toolButton_35 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_35.setObjectName("toolButton_35")
        self.gridLayout.addWidget(self.toolButton_35, 3, 1, 1, 1)
        self.toolButton_27 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_27.setObjectName("toolButton_27")
        self.gridLayout.addWidget(self.toolButton_27, 3, 7, 1, 1)
        self.toolButton_19 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_19.setObjectName("toolButton_19")
        self.gridLayout.addWidget(self.toolButton_19, 1, 6, 1, 1)
        self.toolButton_26 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_26.setObjectName("toolButton_26")
        self.gridLayout.addWidget(self.toolButton_26, 3, 4, 1, 1)
        self.toolButton_44 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_44.setObjectName("toolButton_44")
        self.gridLayout.addWidget(self.toolButton_44, 4, 0, 1, 1)
        self.toolButton_17 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_17.setObjectName("toolButton_17")
        self.gridLayout.addWidget(self.toolButton_17, 1, 7, 1, 1)
        self.toolButton_63 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_63.setObjectName("toolButton_63")
        self.gridLayout.addWidget(self.toolButton_63, 4, 1, 1, 1)
        self.toolButton_74 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_74.setObjectName("toolButton_74")
        self.gridLayout.addWidget(self.toolButton_74, 4, 2, 1, 1)
        self.toolButton_37 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_37.setObjectName("toolButton_37")
        self.gridLayout.addWidget(self.toolButton_37, 2, 5, 1, 1)
        self.toolButton_48 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_48.setObjectName("toolButton_48")
        self.gridLayout.addWidget(self.toolButton_48, 4, 3, 1, 1)
        self.toolButton_71 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_71.setObjectName("toolButton_71")
        self.gridLayout.addWidget(self.toolButton_71, 4, 4, 1, 1)
        self.toolButton_59 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_59.setObjectName("toolButton_59")
        self.gridLayout.addWidget(self.toolButton_59, 4, 5, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 0, 5, 1, 1)
        self.toolButton_33 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_33.setObjectName("toolButton_33")
        self.gridLayout.addWidget(self.toolButton_33, 2, 6, 1, 1)
        self.toolButton_39 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_39.setObjectName("toolButton_39")
        self.gridLayout.addWidget(self.toolButton_39, 2, 9, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 0, 3, 1, 1)
        self.toolButton_32 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_32.setObjectName("toolButton_32")
        self.gridLayout.addWidget(self.toolButton_32, 3, 2, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout.addWidget(self.toolButton_5, 0, 6, 1, 1)
        self.toolButton_29 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_29.setObjectName("toolButton_29")
        self.gridLayout.addWidget(self.toolButton_29, 2, 0, 1, 1)
        self.toolButton_56 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_56.setObjectName("toolButton_56")
        self.gridLayout.addWidget(self.toolButton_56, 4, 6, 1, 1)
        self.toolButton_13 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_13.setObjectName("toolButton_13")
        self.gridLayout.addWidget(self.toolButton_13, 1, 2, 1, 1)
        self.toolButton_12 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_12.setObjectName("toolButton_12")
        self.gridLayout.addWidget(self.toolButton_12, 1, 4, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 0, 0, 1, 1)
        self.toolButton_22 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_22.setObjectName("toolButton_22")
        self.gridLayout.addWidget(self.toolButton_22, 2, 2, 1, 1)
        self.toolButton_23 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_23.setObjectName("toolButton_23")
        self.gridLayout.addWidget(self.toolButton_23, 2, 3, 1, 1)
        self.toolButton_45 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_45.setObjectName("toolButton_45")
        self.gridLayout.addWidget(self.toolButton_45, 4, 7, 1, 1)
        self.toolButton_80 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_80.setObjectName("toolButton_80")
        self.gridLayout.addWidget(self.toolButton_80, 4, 9, 1, 1)
        self.toolButton_69 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_69.setObjectName("toolButton_69")
        self.gridLayout.addWidget(self.toolButton_69, 5, 0, 1, 1)
        self.toolButton_49 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_49.setObjectName("toolButton_49")
        self.gridLayout.addWidget(self.toolButton_49, 4, 8, 1, 1)
        self.toolButton_14 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_14.setObjectName("toolButton_14")
        self.gridLayout.addWidget(self.toolButton_14, 1, 1, 1, 1)
        self.toolButton_15 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_15.setObjectName("toolButton_15")
        self.gridLayout.addWidget(self.toolButton_15, 1, 5, 1, 1)
        self.toolButton_20 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_20.setObjectName("toolButton_20")
        self.gridLayout.addWidget(self.toolButton_20, 1, 8, 1, 1)
        self.toolButton_36 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_36.setObjectName("toolButton_36")
        self.gridLayout.addWidget(self.toolButton_36, 3, 0, 1, 1)
        self.toolButton_10 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_10.setObjectName("toolButton_10")
        self.gridLayout.addWidget(self.toolButton_10, 0, 9, 1, 1)
        self.toolButton_57 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_57.setObjectName("toolButton_57")
        self.gridLayout.addWidget(self.toolButton_57, 5, 4, 1, 1)
        self.toolButton_100 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_100.setObjectName("toolButton_100")
        self.gridLayout.addWidget(self.toolButton_100, 8, 7, 1, 1)
        self.toolButton_83 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_83.setObjectName("toolButton_83")
        self.gridLayout.addWidget(self.toolButton_83, 8, 3, 1, 1)
        self.toolButton_94 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_94.setObjectName("toolButton_94")
        self.gridLayout.addWidget(self.toolButton_94, 8, 8, 1, 1)
        self.toolButton_90 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_90.setObjectName("toolButton_90")
        self.gridLayout.addWidget(self.toolButton_90, 9, 6, 1, 1)
        self.toolButton_81 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_81.setObjectName("toolButton_81")
        self.gridLayout.addWidget(self.toolButton_81, 9, 8, 1, 1)
        self.toolButton_61 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_61.setObjectName("toolButton_61")
        self.gridLayout.addWidget(self.toolButton_61, 5, 8, 1, 1)
        self.toolButton_92 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_92.setObjectName("toolButton_92")
        self.gridLayout.addWidget(self.toolButton_92, 9, 2, 1, 1)
        self.toolButton_85 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_85.setObjectName("toolButton_85")
        self.gridLayout.addWidget(self.toolButton_85, 9, 9, 1, 1)
        self.toolButton_88 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_88.setObjectName("toolButton_88")
        self.gridLayout.addWidget(self.toolButton_88, 8, 4, 1, 1)
        self.toolButton_66 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_66.setObjectName("toolButton_66")
        self.gridLayout.addWidget(self.toolButton_66, 6, 5, 1, 1)
        self.toolButton_51 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_51.setObjectName("toolButton_51")
        self.gridLayout.addWidget(self.toolButton_51, 5, 3, 1, 1)
        self.toolButton_68 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_68.setObjectName("toolButton_68")
        self.gridLayout.addWidget(self.toolButton_68, 5, 7, 1, 1)
        self.toolButton_93 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_93.setObjectName("toolButton_93")
        self.gridLayout.addWidget(self.toolButton_93, 8, 6, 1, 1)
        self.toolButton_50 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_50.setObjectName("toolButton_50")
        self.gridLayout.addWidget(self.toolButton_50, 7, 8, 1, 1)
        self.toolButton_96 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_96.setObjectName("toolButton_96")
        self.gridLayout.addWidget(self.toolButton_96, 9, 0, 1, 1)
        self.toolButton_55 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_55.setObjectName("toolButton_55")
        self.gridLayout.addWidget(self.toolButton_55, 6, 8, 1, 1)
        self.toolButton_95 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_95.setObjectName("toolButton_95")
        self.gridLayout.addWidget(self.toolButton_95, 9, 1, 1, 1)
        self.toolButton_86 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_86.setObjectName("toolButton_86")
        self.gridLayout.addWidget(self.toolButton_86, 9, 4, 1, 1)
        self.toolButton_42 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_42.setObjectName("toolButton_42")
        self.gridLayout.addWidget(self.toolButton_42, 7, 1, 1, 1)
        self.toolButton_70 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_70.setObjectName("toolButton_70")
        self.gridLayout.addWidget(self.toolButton_70, 7, 4, 1, 1)
        self.toolButton_67 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_67.setObjectName("toolButton_67")
        self.gridLayout.addWidget(self.toolButton_67, 5, 6, 1, 1)
        self.toolButton_60 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_60.setObjectName("toolButton_60")
        self.gridLayout.addWidget(self.toolButton_60, 7, 5, 1, 1)
        self.toolButton_89 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_89.setObjectName("toolButton_89")
        self.gridLayout.addWidget(self.toolButton_89, 8, 0, 1, 1)
        self.toolButton_47 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_47.setObjectName("toolButton_47")
        self.gridLayout.addWidget(self.toolButton_47, 7, 3, 1, 1)
        self.toolButton_41 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_41.setObjectName("toolButton_41")
        self.gridLayout.addWidget(self.toolButton_41, 5, 1, 1, 1)
        self.toolButton_98 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_98.setObjectName("toolButton_98")
        self.gridLayout.addWidget(self.toolButton_98, 8, 1, 1, 1)
        self.toolButton_87 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_87.setObjectName("toolButton_87")
        self.gridLayout.addWidget(self.toolButton_87, 9, 7, 1, 1)
        self.toolButton_43 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_43.setObjectName("toolButton_43")
        self.gridLayout.addWidget(self.toolButton_43, 6, 3, 1, 1)
        self.toolButton_46 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_46.setObjectName("toolButton_46")
        self.gridLayout.addWidget(self.toolButton_46, 6, 4, 1, 1)
        self.toolButton_62 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_62.setObjectName("toolButton_62")
        self.gridLayout.addWidget(self.toolButton_62, 5, 5, 1, 1)
        self.toolButton_54 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_54.setObjectName("toolButton_54")
        self.gridLayout.addWidget(self.toolButton_54, 6, 9, 1, 1)
        self.toolButton_78 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_78.setObjectName("toolButton_78")
        self.gridLayout.addWidget(self.toolButton_78, 7, 9, 1, 1)
        self.toolButton_99 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_99.setObjectName("toolButton_99")
        self.gridLayout.addWidget(self.toolButton_99, 8, 9, 1, 1)
        self.toolButton_72 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_72.setObjectName("toolButton_72")
        self.gridLayout.addWidget(self.toolButton_72, 7, 7, 1, 1)
        self.toolButton_75 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_75.setObjectName("toolButton_75")
        self.gridLayout.addWidget(self.toolButton_75, 5, 9, 1, 1)
        self.toolButton_65 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_65.setObjectName("toolButton_65")
        self.gridLayout.addWidget(self.toolButton_65, 6, 0, 1, 1)
        self.toolButton_73 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_73.setObjectName("toolButton_73")
        self.gridLayout.addWidget(self.toolButton_73, 6, 1, 1, 1)
        self.toolButton_58 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_58.setObjectName("toolButton_58")
        self.gridLayout.addWidget(self.toolButton_58, 7, 2, 1, 1)
        self.toolButton_76 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_76.setObjectName("toolButton_76")
        self.gridLayout.addWidget(self.toolButton_76, 6, 2, 1, 1)
        self.toolButton_53 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_53.setObjectName("toolButton_53")
        self.gridLayout.addWidget(self.toolButton_53, 6, 6, 1, 1)
        self.toolButton_91 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_91.setObjectName("toolButton_91")
        self.gridLayout.addWidget(self.toolButton_91, 9, 3, 1, 1)
        self.toolButton_84 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_84.setObjectName("toolButton_84")
        self.gridLayout.addWidget(self.toolButton_84, 9, 5, 1, 1)
        self.toolButton_77 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_77.setObjectName("toolButton_77")
        self.gridLayout.addWidget(self.toolButton_77, 7, 6, 1, 1)
        self.toolButton_79 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_79.setObjectName("toolButton_79")
        self.gridLayout.addWidget(self.toolButton_79, 5, 2, 1, 1)
        self.toolButton_64 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_64.setObjectName("toolButton_64")
        self.gridLayout.addWidget(self.toolButton_64, 6, 7, 1, 1)
        self.toolButton_52 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_52.setObjectName("toolButton_52")
        self.gridLayout.addWidget(self.toolButton_52, 7, 0, 1, 1)
        self.toolButton_82 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_82.setObjectName("toolButton_82")
        self.gridLayout.addWidget(self.toolButton_82, 8, 2, 1, 1)
        self.toolButton_97 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_97.setObjectName("toolButton_97")
        self.gridLayout.addWidget(self.toolButton_97, 8, 5, 1, 1)
        self.toolButton_24 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_24.setObjectName("toolButton_24")
        self.gridLayout.addWidget(self.toolButton_24, 3, 5, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.horizontalLayout_7.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.groupBox)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.horizontalLayout_7.addWidget(self.widget_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_4.addWidget(self.checkBox)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.widget = QtWidgets.QWidget(AnalytesWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButtonCancel = QtWidgets.QPushButton(self.widget)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_3.addWidget(self.pushButtonCancel)
        self.pushButtonBack = QtWidgets.QPushButton(self.widget)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.horizontalLayout_3.addWidget(self.pushButtonBack)
        self.pushButtonNext = QtWidgets.QPushButton(self.widget)
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.horizontalLayout_3.addWidget(self.pushButtonNext)
        self.verticalLayout_6.addWidget(self.widget)

        self.retranslateUi(AnalytesWidget)
        QtCore.QMetaObject.connectSlotsByName(AnalytesWidget)

    def retranslateUi(self, AnalytesWidget):
        _translate = QtCore.QCoreApplication.translate
        AnalytesWidget.setWindowTitle(_translate("AnalytesWidget", "Analytes"))
        self.labelWelcome.setText(_translate("AnalytesWidget", "Step 1: Protocol Setting for \"mTH1 2 9 17 22Treg 17 Plex\""))
        self.labelInfo.setText(_translate("AnalytesWidget", "Instructions:  Name this protocol and select the acquisition settings. Press Next to continue."))
        self.pushButtonInfo.setText(_translate("AnalytesWidget", "info"))
        self.groupBox.setTitle(_translate("AnalytesWidget", "GroupBox"))
        self.pushButton.setText(_translate("AnalytesWidget", "PushButton"))
        self.pushButton_2.setText(_translate("AnalytesWidget", "PushButton"))
        self.toolButton_2.setText(_translate("AnalytesWidget", "2"))
        self.toolButton_40.setText(_translate("AnalytesWidget", "28"))
        self.toolButton_34.setText(_translate("AnalytesWidget", "29"))
        self.toolButton_21.setText(_translate("AnalytesWidget", "39"))
        self.toolButton_25.setText(_translate("AnalytesWidget", "40"))
        self.toolButton_7.setText(_translate("AnalytesWidget", "8"))
        self.toolButton_16.setText(_translate("AnalytesWidget", "20"))
        self.toolButton_28.setText(_translate("AnalytesWidget", "25"))
        self.toolButton_3.setText(_translate("AnalytesWidget", "3"))
        self.toolButton_30.setText(_translate("AnalytesWidget", "37"))
        self.toolButton_31.setText(_translate("AnalytesWidget", "34"))
        self.toolButton_11.setText(_translate("AnalytesWidget", "11"))
        self.toolButton_8.setText(_translate("AnalytesWidget", "5"))
        self.toolButton_9.setText(_translate("AnalytesWidget", "9"))
        self.toolButton_18.setText(_translate("AnalytesWidget", "14"))
        self.toolButton_38.setText(_translate("AnalytesWidget", "22"))
        self.toolButton_35.setText(_translate("AnalytesWidget", "32"))
        self.toolButton_27.setText(_translate("AnalytesWidget", "38"))
        self.toolButton_19.setText(_translate("AnalytesWidget", "17"))
        self.toolButton_26.setText(_translate("AnalytesWidget", "35"))
        self.toolButton_44.setText(_translate("AnalytesWidget", "41"))
        self.toolButton_17.setText(_translate("AnalytesWidget", "18"))
        self.toolButton_63.setText(_translate("AnalytesWidget", "42"))
        self.toolButton_74.setText(_translate("AnalytesWidget", "43"))
        self.toolButton_37.setText(_translate("AnalytesWidget", "26"))
        self.toolButton_48.setText(_translate("AnalytesWidget", "44"))
        self.toolButton_71.setText(_translate("AnalytesWidget", "45"))
        self.toolButton_59.setText(_translate("AnalytesWidget", "46"))
        self.toolButton_6.setText(_translate("AnalytesWidget", "6"))
        self.toolButton_33.setText(_translate("AnalytesWidget", "27"))
        self.toolButton_39.setText(_translate("AnalytesWidget", "30"))
        self.toolButton_4.setText(_translate("AnalytesWidget", "4"))
        self.toolButton_32.setText(_translate("AnalytesWidget", "33"))
        self.toolButton_5.setText(_translate("AnalytesWidget", "7"))
        self.toolButton_29.setText(_translate("AnalytesWidget", "21"))
        self.toolButton_56.setText(_translate("AnalytesWidget", "47"))
        self.toolButton_13.setText(_translate("AnalytesWidget", "13"))
        self.toolButton_12.setText(_translate("AnalytesWidget", "15"))
        self.toolButton.setText(_translate("AnalytesWidget", "1"))
        self.toolButton_22.setText(_translate("AnalytesWidget", "23"))
        self.toolButton_23.setText(_translate("AnalytesWidget", "24"))
        self.toolButton_45.setText(_translate("AnalytesWidget", "48"))
        self.toolButton_80.setText(_translate("AnalytesWidget", "50"))
        self.toolButton_69.setText(_translate("AnalytesWidget", "51"))
        self.toolButton_49.setText(_translate("AnalytesWidget", "49"))
        self.toolButton_14.setText(_translate("AnalytesWidget", "12"))
        self.toolButton_15.setText(_translate("AnalytesWidget", "16"))
        self.toolButton_20.setText(_translate("AnalytesWidget", "19"))
        self.toolButton_36.setText(_translate("AnalytesWidget", "31"))
        self.toolButton_10.setText(_translate("AnalytesWidget", "10"))
        self.toolButton_57.setText(_translate("AnalytesWidget", "55"))
        self.toolButton_100.setText(_translate("AnalytesWidget", "88"))
        self.toolButton_83.setText(_translate("AnalytesWidget", "84"))
        self.toolButton_94.setText(_translate("AnalytesWidget", "89"))
        self.toolButton_90.setText(_translate("AnalytesWidget", "97"))
        self.toolButton_81.setText(_translate("AnalytesWidget", "99"))
        self.toolButton_61.setText(_translate("AnalytesWidget", "59"))
        self.toolButton_92.setText(_translate("AnalytesWidget", "93"))
        self.toolButton_85.setText(_translate("AnalytesWidget", "100"))
        self.toolButton_88.setText(_translate("AnalytesWidget", "85"))
        self.toolButton_66.setText(_translate("AnalytesWidget", "66"))
        self.toolButton_51.setText(_translate("AnalytesWidget", "54"))
        self.toolButton_68.setText(_translate("AnalytesWidget", "58"))
        self.toolButton_93.setText(_translate("AnalytesWidget", "87"))
        self.toolButton_50.setText(_translate("AnalytesWidget", "79"))
        self.toolButton_96.setText(_translate("AnalytesWidget", "91"))
        self.toolButton_55.setText(_translate("AnalytesWidget", "69"))
        self.toolButton_95.setText(_translate("AnalytesWidget", "92"))
        self.toolButton_86.setText(_translate("AnalytesWidget", "95"))
        self.toolButton_42.setText(_translate("AnalytesWidget", "72"))
        self.toolButton_70.setText(_translate("AnalytesWidget", "75"))
        self.toolButton_67.setText(_translate("AnalytesWidget", "57"))
        self.toolButton_60.setText(_translate("AnalytesWidget", "76"))
        self.toolButton_89.setText(_translate("AnalytesWidget", "81"))
        self.toolButton_47.setText(_translate("AnalytesWidget", "74"))
        self.toolButton_41.setText(_translate("AnalytesWidget", "52"))
        self.toolButton_98.setText(_translate("AnalytesWidget", "82"))
        self.toolButton_87.setText(_translate("AnalytesWidget", "98"))
        self.toolButton_43.setText(_translate("AnalytesWidget", "64"))
        self.toolButton_46.setText(_translate("AnalytesWidget", "65"))
        self.toolButton_62.setText(_translate("AnalytesWidget", "56"))
        self.toolButton_54.setText(_translate("AnalytesWidget", "70"))
        self.toolButton_78.setText(_translate("AnalytesWidget", "80"))
        self.toolButton_99.setText(_translate("AnalytesWidget", "90"))
        self.toolButton_72.setText(_translate("AnalytesWidget", "78"))
        self.toolButton_75.setText(_translate("AnalytesWidget", "60"))
        self.toolButton_65.setText(_translate("AnalytesWidget", "61"))
        self.toolButton_73.setText(_translate("AnalytesWidget", "62"))
        self.toolButton_58.setText(_translate("AnalytesWidget", "73"))
        self.toolButton_76.setText(_translate("AnalytesWidget", "63"))
        self.toolButton_53.setText(_translate("AnalytesWidget", "67"))
        self.toolButton_91.setText(_translate("AnalytesWidget", "94"))
        self.toolButton_84.setText(_translate("AnalytesWidget", "96"))
        self.toolButton_77.setText(_translate("AnalytesWidget", "77"))
        self.toolButton_79.setText(_translate("AnalytesWidget", "53"))
        self.toolButton_64.setText(_translate("AnalytesWidget", "68"))
        self.toolButton_52.setText(_translate("AnalytesWidget", "71"))
        self.toolButton_82.setText(_translate("AnalytesWidget", "83"))
        self.toolButton_97.setText(_translate("AnalytesWidget", "86"))
        self.toolButton_24.setText(_translate("AnalytesWidget", "36"))
        self.label_2.setText(_translate("AnalytesWidget", "TextLabel"))
        self.label_3.setText(_translate("AnalytesWidget", "TextLabel"))
        self.pushButton_3.setText(_translate("AnalytesWidget", "PushButton"))
        self.label_4.setText(_translate("AnalytesWidget", "TextLabel"))
        self.label_5.setText(_translate("AnalytesWidget", "TextLabel"))
        self.pushButton_4.setText(_translate("AnalytesWidget", "PushButton"))
        self.label.setText(_translate("AnalytesWidget", "TextLabel"))
        self.checkBox.setText(_translate("AnalytesWidget", "CheckBox"))
        self.pushButtonCancel.setText(_translate("AnalytesWidget", "Cancel"))
        self.pushButtonBack.setText(_translate("AnalytesWidget", "Back"))
        self.pushButtonNext.setText(_translate("AnalytesWidget", "Next"))


