# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.resize(473, 406)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Setting)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetTest = QtWidgets.QWidget(Setting)
        self.widgetTest.setObjectName("widgetTest")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widgetTest)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.widgetTest)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.widgetTest)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.comboBoxSelectTestCOM = QtWidgets.QComboBox(self.widgetTest)
        self.comboBoxSelectTestCOM.setObjectName("comboBoxSelectTestCOM")
        self.horizontalLayout_14.addWidget(self.comboBoxSelectTestCOM)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.widgetTest)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.lineEditSend = QtWidgets.QLineEdit(self.widgetTest)
        self.lineEditSend.setObjectName("lineEditSend")
        self.verticalLayout_2.addWidget(self.lineEditSend)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.widgetTest)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.lineEditReceive = QtWidgets.QLineEdit(self.widgetTest)
        self.lineEditReceive.setObjectName("lineEditReceive")
        self.verticalLayout_3.addWidget(self.lineEditReceive)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 168, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.btnSendMsg = QtWidgets.QPushButton(self.widgetTest)
        self.btnSendMsg.setObjectName("btnSendMsg")
        self.horizontalLayout_13.addWidget(self.btnSendMsg)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout.addWidget(self.widgetTest)
        self.widgetSetting = QtWidgets.QWidget(Setting)
        self.widgetSetting.setObjectName("widgetSetting")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetSetting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.label_9 = QtWidgets.QLabel(self.widgetSetting)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widgetSetting)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBoxMotorStageX = QtWidgets.QComboBox(self.widgetSetting)
        self.comboBoxMotorStageX.setObjectName("comboBoxMotorStageX")
        self.horizontalLayout_2.addWidget(self.comboBoxMotorStageX)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widgetSetting)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBoxMotorStageY = QtWidgets.QComboBox(self.widgetSetting)
        self.comboBoxMotorStageY.setObjectName("comboBoxMotorStageY")
        self.horizontalLayout_3.addWidget(self.comboBoxMotorStageY)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widgetSetting)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboBoxMotorStageZ = QtWidgets.QComboBox(self.widgetSetting)
        self.comboBoxMotorStageZ.setObjectName("comboBoxMotorStageZ")
        self.horizontalLayout_4.addWidget(self.comboBoxMotorStageZ)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widgetSetting)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.comboBoxPump = QtWidgets.QComboBox(self.widgetSetting)
        self.comboBoxPump.setObjectName("comboBoxPump")
        self.horizontalLayout_5.addWidget(self.comboBoxPump)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.widgetSetting)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBoxFilter = QtWidgets.QComboBox(self.widgetSetting)
        self.comboBoxFilter.setObjectName("comboBoxFilter")
        self.horizontalLayout_6.addWidget(self.comboBoxFilter)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.widgetSetting)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.comboBoxCCD = QtWidgets.QComboBox(self.widgetSetting)
        self.comboBoxCCD.setObjectName("comboBoxCCD")
        self.horizontalLayout_7.addWidget(self.comboBoxCCD)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.widgetSetting)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.comboBox_7 = QtWidgets.QComboBox(self.widgetSetting)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_7)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.widgetSetting)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.comboBox_8 = QtWidgets.QComboBox(self.widgetSetting)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_8)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem8 = QtWidgets.QSpacerItem(20, 84, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.btnReset = QtWidgets.QPushButton(self.widgetSetting)
        self.btnReset.setObjectName("btnReset")
        self.horizontalLayout_8.addWidget(self.btnReset)
        self.btnComment = QtWidgets.QPushButton(self.widgetSetting)
        self.btnComment.setObjectName("btnComment")
        self.horizontalLayout_8.addWidget(self.btnComment)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout.addWidget(self.widgetSetting)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "设置"))
        self.label_10.setText(_translate("Setting", "测试："))
        self.label_11.setText(_translate("Setting", "选择串口："))
        self.label_12.setText(_translate("Setting", "发送数据："))
        self.label_13.setText(_translate("Setting", "返回消息："))
        self.btnSendMsg.setText(_translate("Setting", "发送"))
        self.label_9.setText(_translate("Setting", "设置："))
        self.label.setText(_translate("Setting", "X轴电机："))
        self.label_2.setText(_translate("Setting", "Y轴电机："))
        self.label_3.setText(_translate("Setting", "Z轴电机："))
        self.label_4.setText(_translate("Setting", "泵电机："))
        self.label_5.setText(_translate("Setting", "滤光片电机："))
        self.label_6.setText(_translate("Setting", "CCD："))
        self.label_7.setText(_translate("Setting", "波特率："))
        self.comboBox_7.setItemText(0, _translate("Setting", "115200"))
        self.comboBox_7.setItemText(1, _translate("Setting", "76800"))
        self.comboBox_7.setItemText(2, _translate("Setting", "38400"))
        self.comboBox_7.setItemText(3, _translate("Setting", "19200"))
        self.comboBox_7.setItemText(4, _translate("Setting", "9600"))
        self.label_8.setText(_translate("Setting", "超时："))
        self.comboBox_8.setItemText(0, _translate("Setting", "1"))
        self.comboBox_8.setItemText(1, _translate("Setting", "2"))
        self.comboBox_8.setItemText(2, _translate("Setting", "3"))
        self.comboBox_8.setItemText(3, _translate("Setting", "4"))
        self.comboBox_8.setItemText(4, _translate("Setting", "5"))
        self.btnReset.setText(_translate("Setting", "重置"))
        self.btnComment.setText(_translate("Setting", "确定"))


